### ISSUE TITLE
Example code in the GitHub documentation on how to use GoTrue in Swift

### ISSUE THREAD

**Issue by LeoHeuser** [supabase-community/gotrue-swift#10]
As a Supabase user, I want to see an explicit code example in Swift, to be able to set up a basic user management within minutes and have a reference to the JS documentation.
---
Currently the documentation doesn't help me that much as a beginner in Swift and with no experience in JS.
I personally liked the introduction in the PostgREST (see https://github.com/supabase-community/postgrest-swift section "Usage") where you get a basic example to keep the connection to a db up and running. I was able to get data within 20 min. of work based on the PostgRest "tutorial".

I wish for a short documentation of getting started with a basic user management: 
- Create a user with Supabase by providing an e-mail-address and a password (I assume it's the default).
- Assign a session to a user so she or he can INSERT into a db with authored access only (using Supabase RLS templates).

**Comment by AngCosmin** [comment]
Hey @LeoHeuser 👋 
I added an example in the README of this repo: https://github.com/supabase-community/supabase-swift
Let me know if you have any further questions
