### ISSUE TITLE
Sign up returns error even though account is registered successfully

### ISSUE THREAD

**Issue by mhaezaragoza** [supabase-community/gotrue-swift#15]
I'm getting error even though account is successfully registered.

Here's my code and the error: 
<img width="1040" alt="Screen Shot 2022-03-29 at 3 38 16 PM" src="https://user-images.githubusercontent.com/62824325/160559128-b73166b4-368b-4e97-89bd-fc3deed00cb9.png">

I'm using 0.0.4 and I have no problem when using the account to sign in.

**Comment by grdsdev** [comment]
Hi @mhaezaragoza thanks for reporting this.

I wasn't able to reproduce this, can you please inspect the error or just use  a `dump(error)` instead?
Then post result here so I have more info to understand what's happening.

Thanks!

**Comment by mhaezaragoza** [comment]
Hi @grsouza  here

<img width="1046" alt="Screen Shot 2022-03-29 at 5 47 51 PM" src="https://user-images.githubusercontent.com/62824325/160584429-adc39e27-5889-4106-b228-1aba0c4202ac.png">

**Comment by mhaezaragoza** [comment]
hi @grsouza  any update on this? Thanks!

**Comment by grdsdev** [comment]
@mhaezaragoza this has been fixed on #16 but I still need to do some more work on this PR before it lands.

If you wish you could give it a try, a lot of things changed in this PR as we dropped support for older OS versions.
