### ISSUE TITLE
autoRefreshToken not working

### ISSUE THREAD

**Issue by jjlange** [supabase-community/gotrue-swift#19]
I'm currently facing the problem that users get logged out after the JWT Token expires. I assumed the Token gets automatically refreshed when the autoRefreshToken value is set to true but it doesn't. 

Error: 
`PostgrestError(details: nil, hint: nil, code: nil, message: "JWT expired")`

Additionally, some of the examples (sign in/sign out) in the README.md are not working with the newest version and other docs are missing (authEventChange for example).

**Comment by daneden** [comment]
+1, I’ve noticed that `autoRefreshToken` seems to have no effect (using SupabaseClient).

**Comment by grdsdev** [comment]
Closing this in favor of https://github.com/supabase-community/supabase-swift/issues/30
