### ISSUE TITLE
The data couldn’t be read because it isn’t in the correct format(missing Provider case `phone`)

### ISSUE THREAD

**Issue by khamb** [supabase-community/gotrue-swift#38]
## Description
GoTrue fails to decode  `UserIdentity.provider` entity. 

## Fix 
Add `Provider` case `phone`
```
public enum Provider: String, Codable, CaseIterable {
 case phone
}
```

**Comment by grdsdev** [comment]
Released in https://github.com/supabase-community/supabase-swift/releases/tag/0.1.1
