### ISSUE TITLE
Trying to login throws error

### ISSUE THREAD

**Issue by joeldrotleff** [supabase-community/gotrue-swift#44]
Hello I just created a new Supabase project for testing, and tried to login using GoTrue from a new SwiftUI project, running in the iOS simulator. But it just errors out.

# Bug report

## Describe the bug
I tried following the README.

In my project I do:
let auth = GoTrueClient(
    url: SUPABASE_URL, headers: ["apikey": SUPABASE_KEY]
)
Button("Sign Up") {
                Task {
                    try await auth.signUp(email: "myemail@gmail.com", password: "somepassword")
                }
            }

I see this in my device logs:
no Route matched with those values

## To Reproduce
1. Create Supabase project based on the Auth tutorial.
2. Create SwiftUI project based on GoTrue README
3. Notice error.

## System information

- OS: macOS

**Comment by maail** [comment]
@joeldrotleff double check whether you're URL ends in `/auth/v1`. This is needed for the Auth flow. I think that's what you're probably missing. 

The url as an example can be: `https://{your supabase app id}.supabase.co/auth/v1`

**Comment by joeldrotleff** [comment]
Thanks for respnding. That could have been it. I tried again using the supabase-swift library's 'auth' and this time it seems to have gotten through. I got a verification email.

**Comment by grdsdev** [comment]
Hey @joeldrotleff 

When using the supabase-swift library, it automatically adds the `auth/v1` to the URL, but if you need to use the gotrue-siwft directly, you'll have to add it yourself.

**Comment by maail** [comment]
@joeldrotleff if all good from your side feel free to close this.

**Comment by joeldrotleff** [comment]
Ok yea I'll close - thanks

**Comment by joeldrotleff** [comment]
Looks to be working when used in conjunction w/ supabase-swift library
